name: Build OpenWrt/IsoHorns images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ 'wallys_dr5332' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
     # Clean unnecessary files to save disk space
    - name: clean unncessary files to save space
      run: |
        docker rmi `docker images -q`

    - name: Build image for ${{ matrix.target }}
      id: build
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        make -j TARGET=${{ matrix.target }}
    
    - name: Build image for ${{ matrix.target }}
      id: build_image
      run: |
        LOWERCASE_TARGET=`echo ${{ matrix.target }} | tr '[:upper:]' '[:lower:]'`
        HASH=$(git rev-parse --short HEAD)

        BASENAME="$(date +%Y%m%d)-$LOWERCASE_TARGET-main-$HASH"
        TAR_NAME="$BASENAME.tar.gz"
        IMG_NAME="$BASENAME-upgrade.bin"

        echo "IMG_NAME=$IMG_NAME" >> $GITHUB_ENV  # Export IMG_NAME as an environment variable
        echo "::set-output name=IMG_NAME::$IMG_NAME"  # Set output for use in next steps

        # Package the files
        tar cfz "openwrt/tmp/$TAR_NAME" -C openwrt/bin/targets/ .

        echo "::set-output name=TAR_NAME::$TAR_NAME"  # Set output for use in next steps

    - name: Create Release.txt for reference
      run: echo ${{ github.sha }} > Release.txt

    - name: List all .ipk and .bin files in ./
      run: |
        echo "Listing all .ipk and .bin files in openwrt/bin/:"
        find . -type f \( -name "*.ipk" -o -name "*.bin" \)

    - name: Push to the latest release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: latest
        make_latest: true
        files: |
          Release.txt
          openwrt/tmp/${{ steps.build_image.outputs.TAR_NAME }}
          openwrt/tmp/${{ steps.build_image.outputs.IMG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
