name: Build OpenWrt/IsoHorns images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ 'wallys_dr5332' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build image for ${{ matrix.target }}
      id: build_image
      run: |
        ./build.sh ${{ matrix.target }}

        LOWERCASE_TARGET=`echo ${{ matrix.target }} | tr '[:upper:]' '[:lower:]'`
        HASH=$(git rev-parse --short HEAD)

        BASENAME="$(date +%Y%m%d)-$LOWERCASE_TARGET-main-$HASH"
        TAR_NAME="$BASENAME.tar.gz"
        IMG_NAME="$BASENAME-upgrade.bin"
        JSON_NAME="$BASENAME.json"

        echo "IMG_NAME=$IMG_NAME" >> $GITHUB_ENV  # Export IMG_NAME as an environment variable

        # Package the files
        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ .

        echo "::set-output name=img_name::$IMG_NAME"  # Set output for use in next steps

    - name: Create Release.txt for reference
      run: echo ${{ github.sha }} > Release.txt

    - name: Push to the latest release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: latest
        make_latest: true
        files: |
          Release.txt
          openwrt/tmp/${{ steps.build_image.outputs.img_name }}
          latest-upgrade.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
